_welcome:
    path:      /
    defaults:  { _controller: OberonAssignmentBundle:Brewery:index }

_brewery:
    resource: "@OberonAssignmentBundle/Controller/BreweryController.php"
    type:     annotation
    prefix:   /brewery